spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: asdgabaahdstfavassgyhjuuuuutjgddsfadgrtshfgsdhydsrthtrssssssssssf
